@url_dev=http://127.0.0.1:5000/v1/api

### signUp
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop Web",
    "email": "nguyenquocnhat@gmail.com",
    "password": "nhat123"
}